-- MySQL Script generated by MySQL Workbench
-- Sun Jul 25 23:42:32 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Carro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Carro` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Carro` (
  `idCarro` INT NOT NULL AUTO_INCREMENT,
  `nomeCarro` VARCHAR(45) NOT NULL,
  `preco` FLOAT NOT NULL,
  `combustivel` VARCHAR(45) NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `garantia` VARCHAR(45) NOT NULL,
  `lugares` VARCHAR(45) NOT NULL,
  `cambio` VARCHAR(45) NOT NULL,
  `situacao` VARCHAR(45) NOT NULL,
  `consumo` VARCHAR(45) NOT NULL,
  `estoque` INT NOT NULL,
  PRIMARY KEY (`idCarro`),
  UNIQUE INDEX `nomeCarro_UNIQUE` (`nomeCarro` ASC) VISIBLE,
  UNIQUE INDEX `idCarro_UNIQUE` (`idCarro` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Equipamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Equipamentos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Equipamentos` (
  `freioABS` TINYINT NOT NULL,
  `airbags` TINYINT NOT NULL,
  `faroisDeNeblina` TINYINT NOT NULL,
  `arCondicionado` TINYINT NOT NULL,
  `kitMultimidia` TINYINT NOT NULL,
  `retrovisoresEletricos` TINYINT NOT NULL,
  `vidrosEletricos` TINYINT NOT NULL,
  `volanteMultifuncional` TINYINT NOT NULL,
  `controleDeEstabilidade` TINYINT NOT NULL,
  `Carro_idCarro` INT NOT NULL,
  INDEX `fk_Equipamentos_Carro_idx` (`Carro_idCarro` ASC) VISIBLE,
  CONSTRAINT `fk_Equipamentos_Carro`
    FOREIGN KEY (`Carro_idCarro`)
    REFERENCES `mydb`.`Carro` (`idCarro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Endereco` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Endereco` (
  `idEndereco` INT NOT NULL AUTO_INCREMENT,
  `cep` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `rua` VARCHAR(45) NOT NULL,
  `complemento` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEndereco`),
  UNIQUE INDEX `idEndereco_UNIQUE` (`idEndereco` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nomeCliente` VARCHAR(45) NOT NULL,
  `sobrenomeCliente` VARCHAR(45) NOT NULL,
  `cpfCliente` VARCHAR(45) NOT NULL,
  `rgCliente` VARCHAR(45) NOT NULL,
  `telefoneCliente` VARCHAR(45) NULL,
  `celularCliente` VARCHAR(45) NULL,
  `Endereco_idEndereco` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `idCliente_UNIQUE` (`idCliente` ASC) VISIBLE,
  INDEX `fk_Cliente_Endereco1_idx` (`Endereco_idEndereco` ASC) VISIBLE,
  UNIQUE INDEX `cpfCliente_UNIQUE` (`cpfCliente` ASC) VISIBLE,
  UNIQUE INDEX `rgCliente_UNIQUE` (`rgCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Endereco1`
    FOREIGN KEY (`Endereco_idEndereco`)
    REFERENCES `mydb`.`Endereco` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
